AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"
Description: COMMON SERVICES - RENEW APPSYNC API KEY | Automatically renew AppSync API key

Resources:

  RenewAppSyncApiKeyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-appsync-api-key
      Description: COMMON SERVICES - RENEW APPSYNC API KEY | Lambda function to automatically renew API keys for all AppSync GraphQL APIs
      Runtime: nodejs22.x
      Handler: index.handler
      CodeUri: src/renew-appsync-api-key
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          # Retry configuration
          MAX_RETRIES: 3
          RETRY_DELAY_MS: 1000
          # Expiration configuration (days)
          EXPIRATION_DAYS: 365
          # Renewal threshold: renew keys that expire in X days or less
          RENEWAL_THRESHOLD_DAYS: 30
          # Pagination configuration
          PAGINATION_MAX_RESULTS: 25
          # Force renewal of all keys regardless of expiration (true/false)
          FORCE_RENEWAL: "false"
          # Enable sanitization of sensitive data in logs (true/false, default: true)
          ENABLE_SANITIZATION: "true"
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - appsync:ListGraphqlApis
                - appsync:GetGraphqlApi
                - appsync:ListApiKeys
                - appsync:UpdateApiKey
              Resource: '*'
      Events:
        RenewalSchedule:
          Type: Schedule
          Properties:
            Name: !Sub ${AWS::StackName}-renewal-schedule
            Description: COMMON SERVICES - RENEW APPSYNC API KEY | Scheduled event to trigger automatic renewal of AppSync API keys every 300 days
            Schedule: "rate(300 days)"

  RenewAppSyncApiKeyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${RenewAppSyncApiKeyFunction}
      RetentionInDays: 30
