AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"
Description: Automatically renew AppSync API key

Resources:

  RenewApiKeyAppSync:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda in charge of renewing the API KEY of all AppSync.
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: handlers
      Timeout: 100
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - appsync:ListGraphqlApis
                - appsync:GetGraphqlApi
                - appsync:ListApiKeys
                - appsync:UpdateApiKey
              Resource: '*'
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: "rate(300 days)"
      
